### ISSUE TITLE
一个用CKStyle检查代码的例子

### ISSUE THREAD

**Issue by wangjeaf** [wangjeaf/ckstyle-node#20]
## Demo (parse -> check)

此处演示的是代码风格检查功能。

所有的检查项都来自于plugins/*.js的check方法
### 原始CSS代码

``` css
.test1 ul li a {
width:10px;
color:#ffffff;
    -webkit-border-radius:3px;
-moz-border-radius : 3px;
border-radius:3px
}
```
#### 检查结果 1：

<pre>
[ERROR] 1. use less tag in ".test1 ul li a"
[ERROR] 2. css3 prop "-webkit-border-radius" missing some of "-webkit-,-moz-,-o-,std" in ".test1 ul li a"
[ERROR] 3. css3 prop "-moz-border-radius" missing some of "-webkit-,-moz-,-o-,std" in ".test1 ul li a"
[ERROR] 4. css3 prop "border-radius" missing some of "-webkit-,-moz-,-o-,std" in ".test1 ul li a"
 [WARN] 5. do not simply use 1,2,3 as selector, in ".test1 ul li a"
 [WARN] 6. color should in upper case in ".test1 ul li a"
 [WARN] 7. each rule in ".test1 ul li a" need semicolon in the end, "border-radius" has not
  [LOG] 8. css3 prop "-moz-border-radius" should align to right in ".test1 ul li a"
  [LOG] 9. css3 prop "border-radius" should align to right in ".test1 ul li a"
  [LOG] 10. should have 4 spaces before "width" in ".test1 ul li a"
  [LOG] 11. should have 4 spaces before "color" in ".test1 ul li a"
  [LOG] 12. should have (only) one "space" before value of "-webkit-border-radius" in ".test1 ul li a"
  [LOG] 13. should not have "space" after "-moz-border-radius" in ".test1 ul li a"
  [LOG] 14. should have (only) one "space" before value of "border-radius" in ".test1 ul li a"
</pre>

#### 第一次修改后：

``` css
.test-special-word a.a-class {
    width:10px;
    color:#FFFFFF;
    -webkit-border-radius: 3px;
       -moz-border-radius: 3px;
         -o-border-radius: 3px;
            border-radius: 3px;
}
```
#### 再次检查：

<pre>
[ERROR] 1. should not put "HTMLtag" and ".class" together in ".test-special-word a.a-class"
 [WARN] 2. replace "#FFFFFF" with "#FFF" in ".test-special-word a.a-class"
  [LOG] 3. should have (only) one "space" before value of "width" in ".test-special-word a.a-class"
  [LOG] 4. should have (only) one "space" before value of "color" in ".test-special-word a.a-class"
</pre>

#### 符合规范的最终代码

``` css
.test-special-word .a-class {
    width: 10px;
    color: #FFF;
    -webkit-border-radius: 3px;
       -moz-border-radius: 3px;
         -o-border-radius: 3px;
            border-radius: 3px;
}
```
