### ISSUE TITLE
!important 规则的处理

### ISSUE THREAD

**Issue by yisibl** [wangjeaf/ckstyle-node#25]
input:

``` css
.foo {
  margin-top: 10px;
  margin: 20px;
}
```

output

``` css
.foo {
  margin: 20px;
}
```

有 !important 时不合并

input 

``` css
.foo {
  margin-top: 10px !important;
  margin: 20px;
}
```

output

``` css
.foo {
  margin-top: 10px !important;
  margin: 20px;
}
```
