### ISSUE TITLE
层叠规则的处理

### ISSUE THREAD

**Issue by yisibl** [wangjeaf/ckstyle-node#26]
input

``` css
.foo {
  background-color: #999;
  background: url(../img/demo.png) 0 0 no-repeat;
}
```

output

后面覆盖了前面的 background-color ，变成了transparent

``` css
.foo {
  background: url(../img/demo.png) 0 0 no-repeat;
}
```
