### ISSUE TITLE
bootstrap icons失效

### ISSUE THREAD

**Issue by Bosn** [wangjeaf/ckstyle-node#28]
bootstrap icons失效

[http://getbootstrap.com/dist/css/bootstrap.css](http://getbootstrap.com/dist/css/bootstrap.css)

压缩后，icons相关的内容都只剩下编码。
### 复现方法

将[http://getbootstrap.com/dist/css/bootstrap.css](http://getbootstrap.com/dist/css/bootstrap.css)使用ckstyle压缩后，替换[http://getbootstrap.com/components/](http://getbootstrap.com/components/)页面中的[http://getbootstrap.com/dist/css/bootstrap.min.css](http://getbootstrap.com/dist/css/bootstrap.min.css)

**Comment by wangjeaf** [comment]
bug已找到

``` css
.glyphicon-asterisk:before {
    content: '\2a';
}
```

-->

``` css
.glyphicon-asterisk:before {
    content: '\\2a';
}
```

**Comment by Bosn** [comment]
Escaping issues are always be confusing.

**Comment by wangjeaf** [comment]
囧，bug找偏了。。。

``` css
.glyphicon-asterisk:before {
    content: '\\2a';
}
```

这个是CodeMirror在展示代码时加上的\，CKStyle处理完以后，只有一个，没有两个\
继续找这个虫子~~~
