### ISSUE TITLE
压缩@media rule 逗号后面的空白符

### ISSUE THREAD

**Issue by yisibl** [wangjeaf/ckstyle-node#29]
``` css
@media
  only screen and (-o-min-device-pixel-ratio: 2/1), /* Opera */
  only screen and (min--moz-device-pixel-ratio: 2), /* Firefox 16 之前 */
  only screen and (-moz-min-device-pixel-ratio: 2), /* Firefox */
  only screen and (-webkit-min-device-pixel-ratio: 2), /* WebKit */
  only screen and (min-resolution: 192dpi), /* 不支持dppx的浏览器 */
  only screen and (min-resolution: 2dppx) /* 标准 */
{
  .selector{
    background-image:url(@2xaaa.png);/* Retina */
    background-size: 100px 20px;
  }
}
```
